### ISSUE TITLE
Slovakia is missing from the country list

### ISSUE THREAD

**Issue by taggartgorman** [marchah/node-countries#29]
Is this because the iso2 code for Slovakia is the same as the deleted area "Sikkim"?

**Comment by hlopetz** [comment]
just hit that too

**Comment by hlopetz** [comment]
i am not sure about country, but it looks like Sikkim is an Indian state/province. probably, there is a mistake

**Comment by hlopetz** [comment]
there is a PR #30 for your convenience. please review

**Comment by marchah** [comment]
published thanks

**Comment by hlopetz** [comment]
i am not sure what's wrong, but it still returns `null` on `getCountryByName('Slovakia', true)`. i might changed the meta-data in a wrong place. please review

**Comment by marchah** [comment]
@hlopetz are you sure the package is the newest version ?

**Comment by jhonvedo** [comment]
@marchah same problem 
pachage.json 
```
  "dependencies": {   
    "node-countries": "2.1.3",
    "ts-node": "^10.8.0"
  }
```
and when i use `getCountryByName('Slovakia', true)` return `null`

**Comment by marchah** [comment]
Should be fixed now, my fault forgot to run `yarn build` before pushing the package to npm :sweat_smile:
