### ISSUE TITLE
Country Name Translations

### ISSUE THREAD

**Issue by aladdin83** [marchah/node-countries#9]
do you consider localizing country names by adding a translation field like:
```js
translation: {
  [language_code]: string
}
```

**Comment by marchah** [comment]
I wouldn't mind adding that, do you want to do a PR?

**Comment by aladdin83** [comment]
sure, if I can find a reliable source for translations, I will write a script to generate the JSON file.

**Comment by FredChauviere** [comment]
For countries, you can find a "database" in [npm i18n-iso-countries](https://www.npmjs.com/package/i18n-iso-countries).
I also translated the provinces of two major multilingual countries, containing a province definition , that were problematic to display in a French UI: Belgium and Canada. I don't think you need to translalte province names in every language, but at least in the official languages of the country.
[countries.zip](https://github.com/marchah/node-countries/files/7383728/countries.zip)

**Comment by marchah** [comment]
Sorry for the late reply

create a [PR](https://github.com/marchah/node-countries/pull/34) to add the `translation` fields to Belgium and Canada, let me know what you think. I may have miss for changes that you did as I was not able to do a `diff` between your file and mine as the format are different

**Comment by marchah** [comment]
It has been added to the latest release [2.3.0](https://github.com/marchah/node-countries/releases/tag/2.3.0)
